# Generated by Django 3.0.2 on 2020-01-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20200122_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoarea',
            name='geo_json',
            field=models.TextField(null=True),
        ),
    ]
