# Generated by Django 3.0.2 on 2020-01-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20200122_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarea',
            name='is_hot',
            field=models.IntegerField(default=0),
        ),
    ]
