# Generated by Django 3.0.2 on 2020-01-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_geoarea_is_hot'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarea',
            name='cp_latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='geoarea',
            name='cp_longitude',
            field=models.FloatField(default=0),
        ),
    ]
